feat: added CpTimeline widget
cryptoplease/cryptoplease-dart pull request #451
Opened 2022-09-22 08:12 UTC by justinenerio

## Changes

- Added CpTimeline widget 
- Added storybook example

## Related issues

[Fixes: #441 comment](https://github.com/cryptoplease/cryptoplease-dart/pull/441#discussion_r976875407)

## Screenshots
<img width="468" alt="Screen Shot 2022-09-22 at 4 09 49 PM" src="https://user-images.githubusercontent.com/28533130/191693781-d2778b35-3460-4386-8b34-b395ee0eecff.png">

## Checklist

- [] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [x] Screenshots/video added.
- [ ] Tests added.
- [x] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2022-09-24 09:58 UTC, ookami-kb requested changes
There are some weird gaps between tiles:

![image](https://user-images.githubusercontent.com/853356/192091792-bdb2acca-aca4-4820-9ba5-98a509c00435.png)

Also, regarding the widget API – it should be more use-case oriented. Something like this:

```dart
class CpTimelineItem {
  CpTimelineItem({
    required this.title,
    required this.subtitle,
    this.trailing,
  });

  final String title;
  final String subtitle;
  final String? trailing;
}

enum CpTimelineStatus { inProgress, success, failure }

class CpTimeline extends StatelessWidget {
  const CpTimeline({
    super.key,
    required this.items,
    required this.status,
    required this.lastItem,
  });

  final List<CpTimelineItem> items;
  final CpTimelineStatus status;
  final int lastItem;

  @override
  Widget build(BuildContext context) {
    throw UnimplementedError();
  }
}
```

Everything else widget should be able to figure out on its own.

2022-09-25 18:58 UTC, ookami-kb requested changes

2022-09-25 18:58 UTC, ookami-kb commented on packages/cryptoplease_ui/lib/src/timeline_widget.dart
> +    required this.status,
What about `lastItem` parameter? Right now it's not possible to set which item is "active".

2022-09-27 09:45 UTC, justinenerio commented
@ookami-kb i've fixed the weird gap between tiles. also reduced padding between lines, and added the white progress bar on in progress status

2022-09-27 20:26 UTC, ookami-kb commented
@justinenerio I've pushed some changes:

- Added `active` parameter. I remember we were discussing that it's not required for our specific use case, but it's easy to add and it feels more natural from the client's point of view.
- Extracted build methods into separate widgets.
- Added asserts for items list to be non-empty – I think it should be the client's responsibility to provide an empty widget.

2022-09-27 20:39 UTC, ookami-kb approved these changes

2022-09-27 20:39 UTC, merged