feat: add buy and sell flows to app
cryptoplease/cryptoplease-dart pull request #537
Opened 2022-10-20 09:55 UTC by rhbrunetto

## Changes

- Adds buy and sell flows to app
- Migrates to Jupiter API v3 (needed to query based on swapMode)

## Checklist

- [x] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [x] Screenshots/video added.
- [ ] Tests added.
- [x] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2022-11-17 14:19 UTC, ookami-kb commented
@rhbrunetto let's break it down further: `cryptoplease_link` can be a separate PR.

2022-11-21 13:12 UTC, rhbrunetto commented
Converting to draft until we merge #632

2022-12-10 16:33 UTC, ookami-kb requested changes

2022-12-10 18:15 UTC, rhbrunetto commented on packages/cryptoplease/lib/features/token_details/token_details_screen.dart
> +                      ExchangeButtons(token: token),
If the token match is not found the user won't be able to reach this page at all, since it won't show up on the list.

2022-12-10 18:18 UTC, rhbrunetto commented on packages/cryptoplease/lib/features/token_details/token_details_screen.dart
> +                      ExchangeButtons(token: token),
We might check in advance if the token is swappable with USDC, so we can show or not the buttons. Wdyt?

2022-12-11 09:36 UTC, ookami-kb commented on packages/cryptoplease/lib/features/token_details/token_details_screen.dart
> +                      ExchangeButtons(token: token),
I think, for now, just checking if there's a token match in `TokenList` is enough.

2022-12-13 21:04 UTC, ookami-kb requested changes

2022-12-13 21:04 UTC, ookami-kb commented on packages/cryptoplease/lib/features/swap/src/swap/process_swap_screen.dart
> +            _swap = sl<SwapRepository>().watch(state.single);
Why is it single? What if there are multiple items in the set?

Can you make it in the same way as it's done with e.g. `IncomingSplitKeyPaymentScreen`?

2022-12-14 16:45 UTC, ookami-kb approved these changes

2022-12-14 16:45 UTC, merged