fix: Remove commitment from `simulateTransaction` and `sendTransaction`.
cryptoplease/cryptoplease-dart pull request #67
Opened 2021-08-30 15:25 UTC by iharobCP

2021-08-30 21:00 UTC, ookami-kb requested changes
- `simulateTransaction` actually accepts `commitment` parameter: https://docs.solana.com/developing/clients/jsonrpc-api#simulatetransaction
- `signAndSendTransaction` currently accepts `commitment` parameter but doesn't use it.
- `waitForSignatureStatus` doesn't accept `commitment` parameter, but it should be there.

2021-09-01 18:22 UTC, ookami-kb requested changes

2021-09-01 18:22 UTC, ookami-kb commented on packages/solana/lib/src/wallet.dart
>      await _rpcClient.waitForSignatureStatus(signature, TxStatus.finalized);
We should rather use `commitment` parameter and fallback to `TxStatus.finalized` if only it's not set.

2021-09-03 08:34 UTC, antoineherzog approved these changes
LGTM

2021-09-03 09:15 UTC, ookami-kb approved these changes

2021-09-03 09:15 UTC, merged