feat: add tip feature
cryptoplease/cryptoplease-dart pull request #672
Opened 2022-12-09 05:20 UTC by justinenerio

## Changes

- Add tip via QR code

## Checklist

- [ ] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [ ] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

2022-12-09 20:04 UTC, ookami-kb requested changes
You have dependency cycles, please remove them:

```
/app/screens/authenticated/wallet_flow/wallet_flow_screen.dart -> /app/screens/authenticated/wallet_flow/wallet_main_screen.dart -> /app/screens/authenticated/wallet_flow/wallet_flow_screen.dart
/features/incoming_tip_payments/src/presentation/link_listener.dart -> /features/incoming_tip_payments/module.dart -> /features/incoming_tip_payments/src/presentation/link_listener.dart
```

You can check them by running `make deps_graph_all deps_cycles`.

2022-12-10 04:09 UTC, justinenerio commented
@ookami-kb have removed the dependency cycles

2022-12-11 10:11 UTC, ookami-kb requested changes

2022-12-11 10:11 UTC, ookami-kb commented on packages/cryptoplease/lib/features/outgoing_tip_payments/src/bl/bloc.dart
> +    ).toUri();
The link should be wrapped into Firebase deep link (and internal QR code scanner should be able to process it as well).

2022-12-12 05:11 UTC, justinenerio commented
@ookami-kb updated to deeplink and tests

2022-12-14 21:07 UTC, ookami-kb approved these changes

2022-12-14 21:07 UTC, merged